#!/bin/bash
#
# RefWatch Setup Script
# =====================
# Generates Config.xcconfig with your personal Apple Developer identifiers.
# Run this script after cloning the repository.
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
CONFIG_DIR="$PROJECT_ROOT/RefWatchiOS/Config"
CONFIG_FILE="$CONFIG_DIR/Config.xcconfig"
SECRETS_EXAMPLE="$CONFIG_DIR/Secrets.example.xcconfig"
SECRETS_FILE="$CONFIG_DIR/Secrets.xcconfig"

echo ""
echo "RefWatch Setup"
echo "=============="
echo ""
echo "This script will configure your personal Apple Developer identifiers."
echo "These are required to build and run the app on your devices."
echo ""

# Check if config already exists
if [ -f "$CONFIG_FILE" ]; then
    echo "Config.xcconfig already exists."
    read -p "Overwrite? (y/N): " OVERWRITE
    if [[ ! "$OVERWRITE" =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 0
    fi
fi

# Collect values
echo ""
echo "Enter your configuration values:"
echo "(Find your Team ID at https://developer.apple.com/account -> Membership Details)"
echo ""

read -p "Apple Development Team ID: " TEAM_ID
while [ -z "$TEAM_ID" ]; do
    echo "Team ID is required."
    read -p "Apple Development Team ID: " TEAM_ID
done

read -p "Bundle ID prefix (e.g., com.yourcompany): " BUNDLE_PREFIX
while [ -z "$BUNDLE_PREFIX" ]; do
    echo "Bundle ID prefix is required."
    read -p "Bundle ID prefix (e.g., com.yourcompany): " BUNDLE_PREFIX
done

read -p "App Group ID (e.g., group.yourcompany.refwatch): " APP_GROUP
while [ -z "$APP_GROUP" ]; do
    echo "App Group ID is required."
    read -p "App Group ID (e.g., group.yourcompany.refwatch): " APP_GROUP
done

read -p "URL Scheme [refwatch]: " URL_SCHEME
URL_SCHEME=${URL_SCHEME:-refwatch}

# Generate Config.xcconfig
echo ""
echo "Generating Config.xcconfig..."

cat > "$CONFIG_FILE" << EOF
// RefWatch Configuration
// Generated by setup.sh on $(date)
// DO NOT COMMIT THIS FILE

// Include secrets if present (for cloud features)
#include? "Secrets.xcconfig"

// Apple Developer Team ID
DEVELOPMENT_TEAM = $TEAM_ID

// Bundle Identifier Prefix
BUNDLE_ID_PREFIX = $BUNDLE_PREFIX

// App Group Identifier (for reference - must also update entitlements files)
APP_GROUP_ID = $APP_GROUP

// URL Scheme for deep linking
URL_SCHEME = $URL_SCHEME
EOF

echo "Created: $CONFIG_FILE"

# Check for Secrets.xcconfig
if [ ! -f "$SECRETS_FILE" ]; then
    echo ""
    echo "Note: Secrets.xcconfig not found."
    echo "If you want to use cloud features (Supabase, OpenAI), copy the example:"
    echo ""
    echo "  cp $SECRETS_EXAMPLE $SECRETS_FILE"
    echo ""
    echo "Then edit Secrets.xcconfig with your API keys."
fi

# Note about Google Sign-In (optional)
echo ""
echo "Note: For Google Sign-In, add your OAuth client ID to Secrets.xcconfig"
echo "Create credentials at: https://console.cloud.google.com/apis/credentials"

echo ""
echo "Setup complete!"
echo ""
echo "IMPORTANT: App Group Entitlements"
echo "================================="
echo "You need to update the App Group identifier in these entitlements files:"
echo "  - RefWatch Watch App.entitlements"
echo "  - RefWatchWidgetsExtension.entitlements"
echo ""
echo "Replace 'group.refwatch.shared' with your App Group: $APP_GROUP"
echo ""
echo "To create an App Group in Apple Developer portal:"
echo "  1. Go to https://developer.apple.com/account/resources/identifiers"
echo "  2. Click '+' and select 'App Groups'"
echo "  3. Enter your App Group ID: $APP_GROUP"
echo ""
echo "Next steps:"
echo "1. Update entitlements files with your App Group (see above)"
echo "2. (Recommended) Install git hooks to prevent secret commits:"
echo "   ./scripts/install-git-hooks.sh"
echo "3. Open RefWatch.xcodeproj in Xcode"
echo "4. Select your development team if prompted"
echo "5. Build and run on your device or simulator"
echo ""
echo "Build commands:"
echo "  # watchOS"
echo "  xcodebuild -project RefWatch.xcodeproj -scheme 'RefWatch Watch App' \\"
echo "    -destination 'platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)' build"
echo ""
echo "  # iOS"
echo "  xcodebuild -project RefWatch.xcodeproj -scheme 'RefWatchiOS' \\"
echo "    -destination 'platform=iOS Simulator,name=iPhone 15' build"
echo ""
